site_name: Ventures by Calfee
site_url: ""
site_dir: public
use_directory_urls: false

markdown_extensions:
  - attr_list
  - md_in_html

theme:
  name: material
  palette:
    primary: blue grey
    accent: teal